In [1]:
# Import the dependencies.
import pandas as pd
import gmaps
import requests
# Import the API key.
from config import g_key

In [2]:
# Store the CSV you saved created in part one into a DataFrame.
city_data_df = pd.read_csv("weather_data/cities.csv")
city_data_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Puerto Ayora,EC,2022-04-06 14:55:05,-0.7393,-90.3518,78.76,78,45,7.31
1,1,Shimoda,JP,2022-04-06 14:55:06,34.6667,138.9500,53.10,80,100,10.36
2,2,Los Andes,CL,2022-04-06 14:55:06,-32.8337,-70.5983,77.02,24,0,4.47
3,3,Georgetown,MY,2022-04-06 14:55:06,5.4112,100.3354,80.53,89,40,8.05
4,4,Port Alfred,ZA,2022-04-06 14:55:07,-33.5906,26.8910,67.17,63,50,11.99

In [3]:
# Get the data types.
city_data_df.dtypes

City_ID         int64
City           object
Country        object
Date           object
Lat           float64
Lng           float64
Max Temp      float64
Humidity        int64
Cloudiness      int64
Wind Speed    float64
dtype: object

In [4]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

In [5]:
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
temps = []
for temp in max_temp:
    temps.append(max(temp, 0))

In [13]:
# Heatmap of temperature
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
# Assign the figure variable.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, weights=[max(temp, 0) for temp in max_temp], dissipating=False, max_intensity=300, point_radius=4)
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [14]:
# Heatmap of percent humidity
locations = city_data_df[["Lat", "Lng"]]
humidity = city_data_df["Humidity"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [15]:
# Heatmap of percent humidity
locations = city_data_df[["Lat", "Lng"]]
clouds = city_data_df["Cloudiness"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=clouds, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [16]:
# Heatmap of percent humidity
locations = city_data_df[["Lat", "Lng"]]
wind = city_data_df["Wind Speed"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=wind, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [17]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [18]:
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Puerto Ayora,EC,2022-04-06 14:55:05,-0.7393,-90.3518,78.76,78,45,7.31
2,2,Los Andes,CL,2022-04-06 14:55:06,-32.8337,-70.5983,77.02,24,0,4.47
3,3,Georgetown,MY,2022-04-06 14:55:06,5.4112,100.3354,80.53,89,40,8.05
5,5,Porto De Moz,BR,2022-04-06 14:55:07,-1.7483,-52.2383,77.56,86,100,2.44
6,6,Hithadhoo,MV,2022-04-06 14:55:08,-0.6000,73.0833,83.41,64,7,3.18
12,12,Ponerihouen,NC,2022-04-06 14:55:10,-21.0833,165.4000,78.37,93,100,32.55
13,13,Arraial Do Cabo,BR,2022-04-06 14:55:10,-22.9661,-42.0278,82.36,78,75,12.66
14,14,Pijijiapan,MX,2022-04-06 14:55:11,15.7011,-93.2300,87.67,53,1,3.71
17,17,Alappuzha,IN,2022-04-06 14:56:27,9.4900,76.3264,83.75,72,77,6.20
23,23,Bambous Virieux,MU,2022-04-06 14:56:30,-20.3428,57.7575,79.21,78,75,11.50

In [19]:
preferred_cities_df.count()

City_ID       183
City          183
Country       181
Date          183
Lat           183
Lng           183
Max Temp      183
Humidity      183
Cloudiness    183
Wind Speed    183
dtype: int64

In [20]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

               City Country  Max Temp      Lat       Lng Hotel Name
0      Puerto Ayora      EC     78.76  -0.7393  -90.3518
2         Los Andes      CL     77.02 -32.8337  -70.5983
3        Georgetown      MY     80.53   5.4112  100.3354
5      Porto De Moz      BR     77.56  -1.7483  -52.2383
6         Hithadhoo      MV     83.41  -0.6000   73.0833
12      Ponerihouen      NC     78.37 -21.0833  165.4000
13  Arraial Do Cabo      BR     82.36 -22.9661  -42.0278
14       Pijijiapan      MX     87.67  15.7011  -93.2300
17        Alappuzha      IN     83.75   9.4900   76.3264
23  Bambous Virieux      MU     79.21 -20.3428   57.7575

In [21]:
# Set parameters to search for a hotel.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

In [33]:
# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    # Grab the first hotel from the results and store the name.
try:
    hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
except (IndexError):
    print("Hotel not found... skipping.")

{'html_attributions': [],
 'results': [{'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': -6.432146899999999, 'lng': -43.9875122},
    'viewport': {'northeast': {'lat': -6.430799469708497,
      'lng': -43.9861637697085},
     'southwest': {'lat': -6.433497430291502, 'lng': -43.9888617302915}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Casa Pedrosa',
   'place_id': 'ChIJOcKlIGe8hgcRrez6ZNHU_ZM',
   'plus_code': {'compound_code': 'H296+4X Paraibano - State of Maranhão, Brazil',
    'global_code': '685RH296+4X'},
   'reference': 'ChIJOcKlIGe8hgcRrez6ZNHU_ZM',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'vicinity': 'Rua Sete de Setembro, Paraibano'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': -6.429744300000001, 'lng': -43.9804226},
    'viewport': {'northeast': {'lat': -6.428424369708497,
      'lng': -43.97933776970849},
     'southwest': {'lat': -6.431122330291502, 'lng': -43.98203573029149}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Inhumas Hotel',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 3024,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/116011506101495507221">Aluisio Neto</a>'],
     'photo_reference': 'Aap_uEAcukco_HkeHYSf1H03FRe_WjBulYkwBLh9mkral-95oSKcazLnFxnm_4dEyT6799XmndwukM3sSzA1O2AwqUgctaIdetmUZW6fR7zG47eUlzrNe2YAKLkPyaZXGbGtW1JBa9VsRpqVf7vEjfofHmyUdKg9VTCOjXaww4XxFKNPKBzd',
     'width': 4032}],
   'place_id': 'ChIJsabyWAO9hgcREsoK1Ug8mVM',
   'plus_code': {'compound_code': 'H2C9+4R Paraibano - State of Maranhão, Brazil',
    'global_code': '685RH2C9+4R'},
   'rating': 4.3,
   'reference': 'ChIJsabyWAO9hgcREsoK1Ug8mVM',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 3,
   'vicinity': 'Rua Riachuelo, 116, Paraibano'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': -6.431275200000001, 'lng': -43.9883654},
    'viewport': {'northeast': {'lat': -6.429882119708498,
      'lng': -43.98700531970849},
     'southwest': {'lat': -6.432580080291503, 'lng': -43.98970328029149}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Casa Marinheiro',
   'place_id': 'ChIJXwX2DWe8hgcRN5JBOpJkOmY',
   'plus_code': {'compound_code': 'H296+FM Paraibano, State of Maranhão, Brazil',
    'global_code': '685RH296+FM'},
   'reference': 'ChIJXwX2DWe8hgcRN5JBOpJkOmY',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'vicinity': 'Brazil'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': -6.427329200000001,
     'lng': -43.98888099999999},
    'viewport': {'northeast': {'lat': -6.426009019708498,
      'lng': -43.9875178697085},
     'southwest': {'lat': -6.428706980291502, 'lng': -43.99021583029149}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Casa Mendes',
   'place_id': 'ChIJt6TsWFy8hgcRcK7o17FXDes',
   'plus_code': {'compound_code': 'H2F6+3C Paraibano, State of Maranhão, Brazil',
    'global_code': '685RH2F6+3C'},
   'reference': 'ChIJt6TsWFy8hgcRcK7o17FXDes',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'vicinity': 'Brazil'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': -6.426593599999999, 'lng': -43.9895712},
    'viewport': {'northeast': {'lat': -6.425215969708498,
      'lng': -43.9881675197085},
     'southwest': {'lat': -6.427913930291503, 'lng': -43.9908654802915}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Pousada Vitória',
   'place_id': 'ChIJuVPZkVy8hgcRsq6dWDw2h6o',
   'plus_code': {'compound_code': 'H2F6+95 Paraibano, State of Maranhão, Brazil',
    'global_code': '685RH2F6+95'},
   'rating': 4.7,
   'reference': 'ChIJuVPZkVy8hgcRsq6dWDw2h6o',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 3,
   'vicinity': 'Brazil'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': -6.4248717, 'lng': -43.9897768},
    'viewport': {'northeast': {'lat': -6.423537169708498,
      'lng': -43.9884516697085},
     'southwest': {'lat': -6.426235130291502, 'lng': -43.9911496302915}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Pousada São Luis',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 530,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/117623418983899185752">Pousada São Luis</a>'],
     'photo_reference': 'Aap_uECeAnefTjOliyr5YhgM2QKrMWeVb0gF1Yol-0PtjhVVnhFis4SqTn9n947FHrFsrz_VsleSWZ-G3Zbu__9C64cdnpqz5bAAxUex6UF5B-B6e3i0ii6QEj_eUy2khPFoV5KMNVeam-Kq4C59F_07GYOq42ZGd7VMRWIifR06rul1A6Oj',
     'width': 897}],
   'place_id': 'ChIJ86-9H_u9hgcRODlk8Xy4xPE',
   'plus_code': {'compound_code': 'H2G6+33 Paraibano - State of Maranhão, Brazil',
    'global_code': '685RH2G6+33'},
   'rating': 4.3,
   'reference': 'ChIJ86-9H_u9hgcRODlk8Xy4xPE',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 23,
   'vicinity': 'Atrás do Posto Petrovia - Rua Boa Vista - centro, Paraibano'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': -6.426561699999999, 'lng': -43.9928903},
    'viewport': {'northeast': {'lat': -6.425212719708497,
      'lng': -43.9915413197085},
     'southwest': {'lat': -6.4279106802915, 'lng': -43.9942392802915}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Paraibano-ma',
   'place_id': 'ChIJAbylldu9hgcRJVm4PbQWFTc',
   'plus_code': {'compound_code': 'H2F4+9R Paraibano - State of Maranhão, Brazil',
    'global_code': '685RH2F4+9R'},
   'reference': 'ChIJAbylldu9hgcRJVm4PbQWFTc',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'vicinity': 'Avenida São Luis, Paraibano'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': -6.406633299999998, 'lng': -43.9961739},
    'viewport': {'northeast': {'lat': -6.405255469708497,
      'lng': -43.9950718697085},
     'southwest': {'lat': -6.407953430291501, 'lng': -43.9977698302915}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/camping-71.png',
   'icon_background_color': '#4DB546',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/camping_pinlet',
   'name': 'Chácara do Baxim',
   'photos': [{'height': 8000,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/101529061808450122808">Mateus Paiva</a>'],
     'photo_reference': 'Aap_uEDmQxMcUIuS4HKgkg4TlsmBy_RLH4PW10iIJ2TsXuL39IY0Pqjaj_TGAKqZOIMpHSGIWgGRA2hVAAwjVMWEIjvHWxoktSWsBtixJnAz90x7xvP97dHgII0lBNqELe5bW85EjgZXH3QT7tTP-ps7M3RKe02Cv2wesqp8o-n2mQPRsKB7',
     'width': 6000}],
   'place_id': 'ChIJWWqA8169hgcRSASitX_LU9Y',
   'rating': 5,
   'reference': 'ChIJWWqA8169hgcRSASitX_LU9Y',
   'scope': 'GOOGLE',
   'types': ['campground',
    'lodging',
    'park',
    'point_of_interest',
    'establishment'],
   'user_ratings_total': 2,
   'vicinity': 'H2V3+8G, Paraibano'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': -6.409760299999999, 'lng': -44.0041895},
    'viewport': {'northeast': {'lat': -6.408261119708498,
      'lng': -44.0028200197085},
     'southwest': {'lat': -6.410959080291502, 'lng': -44.0055179802915}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Haras dona Terezinha',
   'place_id': 'ChIJT5jFbmi9hgcRcguzwr1RFxk',
   'plus_code': {'compound_code': 'HXRW+38 Paraibano - State of Maranhão, Brazil',
    'global_code': '685QHXRW+38'},
   'reference': 'ChIJT5jFbmi9hgcRcguzwr1RFxk',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'vicinity': 'Unnamed Road, Paraibano'}],
 'status': 'OK'}

In [34]:
hotel_df.head(10)

,City,Country,Max Temp,Lat,Lng,Hotel Name
0,Puerto Ayora,EC,78.76,-0.7393,-90.3518,Finch Bay Galapagos Hotel
2,Los Andes,CL,77.02,-32.8337,-70.5983,Hotel Los Andes
3,Georgetown,MY,80.53,5.4112,100.3354,Cititel Penang
5,Porto De Moz,BR,77.56,-1.7483,-52.2383,Dormitório labelle
6,Hithadhoo,MV,83.41,-0.6000,73.0833,Scoop Guest House
12,Ponerihouen,NC,78.37,-21.0833,165.4000,Camping de Tiakan
13,Arraial Do Cabo,BR,82.36,-22.9661,-42.0278,Pousada Porto Praia
14,Pijijiapan,MX,87.67,15.7011,-93.2300,Hotel Rosita
17,Alappuzha,IN,83.75,9.4900,76.3264,Panoramic Sea Resort
23,Bambous Virieux,MU,79.21,-20.3428,57.7575,Casa Tia Villa

In [36]:
# Add a heatmap of temperature for the vacation spots and marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,
             dissipating=False, max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [38]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""
# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [39]:
# Add a heatmap of temperature for the vacation spots and a pop-up marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))